<?php
include("include/connection.php");
include('simple_html_dom.php');
$html = file_get_html('http://www.localsearch.ae/en/profile/Vilafortuny-Laser-Centre/704912');
//echo $title = $html->find(".tableCell .title",0)->innertext;
//echo $address = $html->find(".tableCell .line1",0)->innertext;
//echo $landmark = $html->find(".tableCell .line2",0)->innertext;
//echo $zipcode = $html->find("span.tableCell",0)->innertext;
//echo $phone_no = $html->find(".telephone span.tableCell",0)->innertext;
//echo $fax_no = $html->find(".telephone span.tableCell",1)->innertext;
//echo $iframe = $html->find("#map-canvas",0)->outertext;
echo $iframe = $html->find("script",0)->innertext;
echo $iframe = $html->find("script",1)->innertext;
echo $iframe = $html->find("script",2)->innertext;
echo $iframe = $html->find("script",3)->innertext;
echo $iframe = $html->find("script",4)->innertext;
echo $iframe = $html->find("script",5)->innertext;
echo $iframe = $html->find("script",6)->innertext;
echo $iframe = $html->find("script",7)->innertext;
echo $iframe = $html->find("script",8)->innertext;
echo $iframe = $html->find("script",9)->innertext;
echo $iframe = $html->find("script",10)->innertext;
echo $iframe = $html->find("script",11)->innertext;
echo $iframe = $html->find("script",12)->innertext;
echo $iframe = $html->find("script",13)->innertext;
echo $iframe = $html->find("script",14)->innertext;
echo $iframe = $html->find("script",15)->innertext;
echo $iframe = $html->find("script",16)->innertext;
echo $iframe = $html->find("script",17)->innertext;
echo $iframe = $html->find("script",18)->innertext;
echo $iframe = $html->find("script",19)->innertext;
echo $iframe = $html->find("script",20)->innertext;
echo $iframe = $html->find("script",21)->innertext;
echo $iframe = $html->find("script",22)->innertext;
echo $iframe = $html->find("script",23)->innertext;
echo $iframe = $html->find("script",24)->innertext;
echo $iframe = $html->find("script",25)->innertext;
echo $iframe = $html->find("script",26)->innertext;

